const STORAGE_NAME = '@matchmaking';
const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_APPOINTMENT = `${STORAGE_NAME}:appointment`;

export { COLLECTION_USER, COLLECTION_APPOINTMENT };
